### ISSUE TITLE
TestResourceTest failures on Jenkins

### ISSUE THREAD

**Issue by davidsowerby** [davidsowerby/q3c-testUtil#20]
test resource

> uk.q3c.util.testutil.InvalidProjectPathException: /var/jenkins_home/jobs/q3c-testUtil/q3c-testUtil/src/test/resources
>     at uk.q3c.util.testutil.TestResource.testFolder(TestResource.java:126)
>     at uk.q3c.util.testutil.TestResource.testResourceRootDir(TestResource.java:108)
>     at TestResourceTest.test resource(TestResourceTest.groovy:27)

testJavaRootDir

> uk.q3c.util.testutil.InvalidProjectPathException: /var/jenkins_home/jobs/q3c-testUtil/q3c-testUtil/src/test/java
>     at uk.q3c.util.testutil.TestResource.testFolder(TestResource.java:126)
>     at uk.q3c.util.testutil.TestResource.testJavaRootDir(TestResource.java:54)
>     at TestResourceTest.testJavaRootDir(TestResourceTest.groovy:16)

**Comment by davidsowerby** [comment]
No longer relevant
